baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
progress = false
custom_theme = "stylesheets/source/hull-blue.scss"
custom_theme_compile = true
margin = 0.1